IP_ADDRESS = "hostname -I | awk '{print $1}'"
CPU_MODEL = """lscpu | grep 'Model name' | cut -f 2 -d ":" | awk '{$1=$1}1'"""
CPU_LOAD = "top -bn1 | awk 'NR<4 && tolower($0) ~ /cpu/ {print 100-$8}'"
NETWORK_INTERFACE = "/sbin/route -n | awk '/^0.0.0.0/ {print $NF}'"
HOSTNAME = "hostname"
MAC_ADDRESS = "ifconfig | grep 'ether' | awk '{print $2}'"
ARCHITECTURE = "uname -m"
MODEL = """cat /proc/cpuinfo | grep "Model" | cut -f 2 -d ":" | awk '{$1=$1};1'"""
MEMORY = "free --mega | awk '/^Mem:/ {print $2}'"
USED_MEMORY = "free --mega | awk '/^Mem:/ {print $3}'"
FREE_MEMORY = "free --mega | awk '/^Mem:/ {print $4}'"
USED_MEMORY_PERCENTAGE = "echo $(free | awk '/^Mem:/ {print $3}') $(free | awk '/^Mem:/ {print $2}') | awk '{ print ($1/$2) * 100 }'"
STORAGE = """df -h | awk '$6 == "/" {print $2}'"""
USED_STORAGE = """df -h | awk '$6 == "/" {print $3}'"""
FREE_STORAGE = """df -h | awk '$6 == "/" {print $4}'"""
USED_STORAGE_PERCENTAGE = """df -h | awk '$6 == "/" {print $5}'"""
CPU_TEMPERATURE = "cat /sys/class/thermal/thermal_zone0/temp"
OPERATING_SYSTEM = """cat /etc/os-release | grep "PRETTY_NAME" | awk '{split($0, a, "="); print a[2]}' | tr -d '"'"""
UPTIME = "uptime | awk '{print $3}' | tr -d ','"